import React, { useState } from 'react';
import { X, Download, Copy, Check, FileCode, FileText } from 'lucide-react';
import { AuditReportResult } from '../types.ts';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: AuditReportResult | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, report }) => {
  const [format, setFormat] = useState<'MARKDOWN' | 'JSON'>('MARKDOWN');
  const [isCopied, setIsCopied] = useState(false);

  if (!isOpen || !report) return null;

  const generateMarkdown = () => {
    return `# RevRecover AI — Revenue Leakage & Churn Audit Report
**Company:** ${report.companyName}
**Industry:** ${report.industry}
**Audit Date:** ${new Date(report.timestamp).toLocaleString()}
**Engine:** ${report.modelDiagnostics.modelUsed}

---

## 1. Executive Financial Summary
${report.executiveSummary}

* **Total MRR at Risk:** $${report.metrics.totalMrrAtRisk.toLocaleString()} ($${report.metrics.totalAnnualLeakage.toLocaleString()} ARR)
* **Involuntary Churn Leakage:** $${report.metrics.involuntaryChurnMrr.toLocaleString()} (${report.metrics.involuntaryPercentage}%)
* **Voluntary Churn Leakage:** $${report.metrics.voluntaryChurnMrr.toLocaleString()} (${report.metrics.voluntaryPercentage}%)
* **Projected Recoverable MRR:** +$${report.metrics.projectedRecoverableMrr.toLocaleString()} ($${report.metrics.projectedAnnualRecovery.toLocaleString()} ARR)
* **Recovery Confidence Score:** ${report.metrics.recoveryConfidenceScore}%

---

## 2. Root-Cause Diagnostic Findings
${report.diagnostics.map((d, i) => `
### ${i + 1}. [${d.severity}] ${d.headline}
* **Category:** ${d.category}
* **MRR at Stake:** $${d.affectedMrr.toLocaleString()}
* **Estimated Win Potential:** ${d.estimatedRecoveryRate}%
* **Root Cause Analysis:** ${d.rootCauseAnalysis}
* **Immediate Remedy:** ${d.immediateRemedy}
* **Systemic Prevention:** ${d.systemicPrevention}
`).join('\n')}

---

## 3. Retention Playbooks
${report.playbooks.map((p, i) => `
### Playbook ${i + 1}: ${p.cohort}
* **Strategy Type:** ${p.strategyType} (${p.channel})
* **Target MRR:** $${p.targetMrr.toLocaleString()} (Est. Win Rate: ${p.estimatedWinRate}%)
* **Tactical Concession:** ${p.incentiveOffer}
* **Subject:** ${p.subjectOrHeader}

\`\`\`
${p.copyOrScript}
\`\`\`

**Implementation Steps:**
${p.implementationSteps.map(s => `- ${s}`).join('\n')}
`).join('\n')}

---
*Generated by RevRecover AI — Built for HackOnVibe August 2026*
`;
  };

  const exportContent = format === 'JSON' ? JSON.stringify(report, null, 2) : generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(exportContent);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([exportContent], { type: format === 'JSON' ? 'application/json' : 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RevRecover_Audit_${report.companyName.replace(/\s+/g, '_')}_${Date.now()}.${format === 'JSON' ? 'json' : 'md'}`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-2xl w-full max-h-[85vh] flex flex-col overflow-hidden animate-in fade-in zoom-in-95 duration-150">
        {/* Header */}
        <div className="p-4 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Download className="w-4 h-4 text-slate-700" />
            <h3 className="text-sm font-bold text-slate-900 font-display">Export Forensic Audit Report</h3>
          </div>
          <button onClick={onClose} className="p-1 text-slate-400 hover:text-slate-650 rounded cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Controls */}
        <div className="px-6 py-3 bg-white border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setFormat('MARKDOWN')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                format === 'MARKDOWN' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-750 hover:bg-slate-200'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Markdown (.md)</span>
            </button>
            <button
              onClick={() => setFormat('JSON')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer ${
                format === 'JSON' ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-750 hover:bg-slate-200'
              }`}
            >
              <FileCode className="w-3.5 h-3.5" />
              <span>Raw JSON</span>
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-100 hover:bg-slate-200 text-slate-800 border border-slate-250 transition-colors cursor-pointer"
            >
              {isCopied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{isCopied ? 'Copied' : 'Copy All'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white transition-colors cursor-pointer"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Preview */}
        <div className="p-6 overflow-y-auto flex-1 bg-slate-900 font-mono text-xs text-slate-200 leading-relaxed border-t border-slate-200">
          <pre className="whitespace-pre-wrap">{exportContent}</pre>
        </div>
      </div>
    </div>
  );
};
